/**
 * Maps free-text feature/amenity input (any language) to `property.json` keys under `tags.*`.
 * Keys are lowercased for lookup.
 */
export const PROPERTY_TAG_ALIAS: Record<string, string> = {
  school: 'school',
  школа: 'school',
  'مدرسة': 'school',
  gym: 'gym',
  'gymnasium': 'gym',
  спортзал: 'gym',
  фитнес: 'gym',
  'fitness center': 'gym',
  'fitness centre': 'gym',
  'صالة رياضية': 'gym',
  pool: 'pool',
  бассейн: 'pool',
  'swimming pool': 'pool',
  'مسبح': 'pool',
  balcony: 'balcony',
  балкон: 'balcony',
  'شرفة': 'balcony',
  terrace: 'terrace',
  терраса: 'terrace',
  'سطح': 'terrace',
  parking: 'parking',
  парковка: 'parking',
  'موقف سيارات': 'parking',
  garden: 'garden',
  сад: 'garden',
  'حديقة': 'garden',
  'sea view': 'seaView',
  'вид на море': 'seaView',
  'إطلالة بحرية': 'seaView',
  'city view': 'cityView',
  'вид на город': 'cityView',
  'إطلالة على المدينة': 'cityView',
  furnished: 'furnished',
  меблирован: 'furnished',
  меблированная: 'furnished',
  'مفروش': 'furnished',
  unfurnished: 'unfurnished',
  'без мебели': 'unfurnished',
  'غير مفروش': 'unfurnished',
  security: 'security',
  охрана: 'security',
  'أمن': 'security',
  concierge: 'concierge',
  консьерж: 'concierge',
  'خدمة استقبال': 'concierge',
  jacuzzi: 'jacuzzi',
  джакузи: 'jacuzzi',
  'جاكوزي': 'jacuzzi',
  sauna: 'sauna',
  сауна: 'sauna',
  'ساونا': 'sauna',
  elevator: 'elevator',
  lift: 'elevator',
  лифт: 'elevator',
  'مصعد': 'elevator',
  'maid room': 'maidRoom',
  'комната прислуги': 'maidRoom',
  'غرفة خادمة': 'maidRoom',
  'walk-in closet': 'walkInCloset',
  'гардеробная': 'walkInCloset',
  'غرفة ملابس': 'walkInCloset',
  'smart home': 'smartHome',
  'умный дом': 'smartHome',
  'منزل ذكي': 'smartHome',
  'central ac': 'centralAc',
  'central a/c': 'centralAc',
  'кондиционер': 'centralAc',
  'تكييف مركزي': 'centralAc',
  'built-in kitchen': 'builtInKitchen',
  'встроенная кухня': 'builtInKitchen',
  'مطبخ مدمج': 'builtInKitchen',
  'children playground': 'childrenPlayground',
  'детская площадка': 'childrenPlayground',
  'ملعب أطفال': 'childrenPlayground',
  'bbq area': 'bbqArea',
  'зона барбекю': 'bbqArea',
  'منطقة شواء': 'bbqArea',
  'pet friendly': 'petFriendly',
  'можно с животными': 'petFriendly',
  'مسموح بالحيوانات': 'petFriendly',
}

/**
 * Canonical SEO entities used for deterministic meta generation.
 * These keys are language-agnostic and mapped from free-form input aliases.
 */
export const PROPERTY_SEO_ALIAS_TO_KEY: Record<string, string> = {
  // Districts / areas
  downtown: 'districtDowntownDubai',
  'dubai downtown': 'districtDowntownDubai',
  'downtown dubai': 'districtDowntownDubai',
  даунтаун: 'districtDowntownDubai',
  'даунтаун дубай': 'districtDowntownDubai',
  'وسط المدينة': 'districtDowntownDubai',
  'وسط مدينة دبي': 'districtDowntownDubai',
  marina: 'districtDubaiMarina',
  'dubai marina': 'districtDubaiMarina',
  марина: 'districtDubaiMarina',
  'дубай марина': 'districtDubaiMarina',
  'مرسى دبي': 'districtDubaiMarina',
  'dubai creek harbour': 'districtDubaiCreekHarbour',
  'creek harbour': 'districtDubaiCreekHarbour',
  'дубай крик харбор': 'districtDubaiCreekHarbour',
  'خور دبي': 'districtDubaiCreekHarbour',
  'business bay': 'districtBusinessBay',
  'бизнес бей': 'districtBusinessBay',
  'الخليج التجاري': 'districtBusinessBay',
  'palm jumeirah': 'districtPalmJumeirah',
  пальма: 'districtPalmJumeirah',
  'пальма джумейра': 'districtPalmJumeirah',
  'نخلة جميرا': 'districtPalmJumeirah',
  jvc: 'districtJvc',
  'jumeirah village circle': 'districtJvc',
  'джумейра вилладж циркл': 'districtJvc',
  'قرية جميرا الدائرية': 'districtJvc',
  jlt: 'districtJlt',
  'jumeirah lake towers': 'districtJlt',
  'джумейра лейк тауэрс': 'districtJlt',
  'أبراج بحيرات جميرا': 'districtJlt',
  'dubai hills': 'districtDubaiHills',
  'dubai hills estate': 'districtDubaiHills',
  'дубай хиллс': 'districtDubaiHills',
  'دبي هيلز': 'districtDubaiHills',
  // Property type
  apartment: 'typeApartment',
  flat: 'typeApartment',
  квартира: 'typeApartment',
  شقة: 'typeApartment',
  villa: 'typeVilla',
  вилла: 'typeVilla',
  فيلا: 'typeVilla',
  townhouse: 'typeTownhouse',
  таунхаус: 'typeTownhouse',
  'تاون هاوس': 'typeTownhouse',
  penthouse: 'typePenthouse',
  пентхаус: 'typePenthouse',
  بنتهاوس: 'typePenthouse',
  studio: 'typeStudio',
  студия: 'typeStudio',
  استوديو: 'typeStudio',
  office: 'typeOffice',
  офис: 'typeOffice',
  مكتب: 'typeOffice',
  retail: 'typeRetail',
  ритейл: 'typeRetail',
  'магазин': 'typeRetail',
  تجزئة: 'typeRetail',
  warehouse: 'typeWarehouse',
  склад: 'typeWarehouse',
  مستودع: 'typeWarehouse',
  land: 'typeLand',
  участок: 'typeLand',
  أرض: 'typeLand',
  // Attributes
  modern: 'attrModern',
  современный: 'attrModern',
  современная: 'attrModern',
  حديث: 'attrModern',
  luxury: 'attrLuxury',
  premium: 'attrLuxury',
  люкс: 'attrLuxury',
  премиум: 'attrLuxury',
  فاخر: 'attrLuxury',
  'new build': 'attrNewBuild',
  newbuild: 'attrNewBuild',
  новостройка: 'attrNewBuild',
  'новая постройка': 'attrNewBuild',
  'بناء جديد': 'attrNewBuild',
  furnished: 'attrFurnished',
  меблированная: 'attrFurnished',
  مفروش: 'attrFurnished',
  'sea view': 'attrSeaView',
  'вид на море': 'attrSeaView',
  'إطلالة بحرية': 'attrSeaView',
  'city view': 'attrCityView',
  'вид на город': 'attrCityView',
  'إطلالة على المدينة': 'attrCityView',
  waterfront: 'attrWaterfront',
  'у воды': 'attrWaterfront',
  'على الواجهة المائية': 'attrWaterfront',
  investment: 'attrInvestment',
  инвестиции: 'attrInvestment',
  استثمار: 'attrInvestment',
  // Direction
  north: 'directionNorth',
  север: 'directionNorth',
  شمال: 'directionNorth',
  south: 'directionSouth',
  юг: 'directionSouth',
  جنوب: 'directionSouth',
  east: 'directionEast',
  восток: 'directionEast',
  شرق: 'directionEast',
  west: 'directionWest',
  запад: 'directionWest',
  غرب: 'directionWest',
  central: 'directionCentral',
  center: 'directionCentral',
  центр: 'directionCentral',
  'وسط': 'directionCentral',
}

export const PROPERTY_SEO_CANONICAL_LABELS: Record<
  string,
  { en: string; ru: string; ar: string }
> = {
  districtDowntownDubai: { en: 'Downtown Dubai', ru: 'Даунтаун Дубай', ar: 'وسط مدينة دبي' },
  districtDubaiMarina: { en: 'Dubai Marina', ru: 'Дубай Марина', ar: 'مرسى دبي' },
  districtDubaiCreekHarbour: {
    en: 'Dubai Creek Harbour',
    ru: 'Дубай Крик Харбор',
    ar: 'خور دبي',
  },
  districtBusinessBay: { en: 'Business Bay', ru: 'Бизнес Бэй', ar: 'الخليج التجاري' },
  districtPalmJumeirah: { en: 'Palm Jumeirah', ru: 'Пальма Джумейра', ar: 'نخلة جميرا' },
  districtJvc: { en: 'Jumeirah Village Circle', ru: 'JVC', ar: 'قرية جميرا الدائرية' },
  districtJlt: { en: 'Jumeirah Lake Towers', ru: 'JLT', ar: 'أبراج بحيرات جميرا' },
  districtDubaiHills: { en: 'Dubai Hills', ru: 'Дубай Хиллс', ar: 'دبي هيلز' },
  typeApartment: { en: 'Apartment', ru: 'Квартира', ar: 'شقة' },
  typeVilla: { en: 'Villa', ru: 'Вилла', ar: 'فيلا' },
  typeTownhouse: { en: 'Townhouse', ru: 'Таунхаус', ar: 'تاون هاوس' },
  typePenthouse: { en: 'Penthouse', ru: 'Пентхаус', ar: 'بنتهاوس' },
  typeStudio: { en: 'Studio', ru: 'Студия', ar: 'استوديو' },
  typeOffice: { en: 'Office', ru: 'Офис', ar: 'مكتب' },
  typeRetail: { en: 'Retail', ru: 'Ритейл', ar: 'تجزئة' },
  typeWarehouse: { en: 'Warehouse', ru: 'Склад', ar: 'مستودع' },
  typeLand: { en: 'Land', ru: 'Участок', ar: 'أرض' },
  attrModern: { en: 'Modern', ru: 'современная', ar: 'حديثة' },
  attrLuxury: { en: 'Luxury', ru: 'премиальная', ar: 'فاخرة' },
  attrNewBuild: { en: 'New Build', ru: 'новостройка', ar: 'بناء جديد' },
  attrFurnished: { en: 'Furnished', ru: 'с мебелью', ar: 'مفروشة' },
  attrSeaView: { en: 'Sea View', ru: 'вид на море', ar: 'إطلالة بحرية' },
  attrCityView: { en: 'City View', ru: 'вид на город', ar: 'إطلالة على المدينة' },
  attrWaterfront: { en: 'Waterfront', ru: 'у воды', ar: 'واجهة مائية' },
  attrInvestment: { en: 'Investment', ru: 'инвестиционная', ar: 'استثمارية' },
  directionNorth: { en: 'North', ru: 'север', ar: 'الشمال' },
  directionSouth: { en: 'South', ru: 'юг', ar: 'الجنوب' },
  directionEast: { en: 'East', ru: 'восток', ar: 'الشرق' },
  directionWest: { en: 'West', ru: 'запад', ar: 'الغرب' },
  directionCentral: { en: 'Central', ru: 'центр', ar: 'الوسط' },
}

export function resolvePropertyTagI18nKey(raw: string): string | null {
  const key = raw.trim().toLowerCase()
  if (key.startsWith('tags.')) {
    const tail = key.slice('tags.'.length)
    return tail ? `tags.${tail}` : null
  }
  const slug = PROPERTY_TAG_ALIAS[key]
  return slug ? `tags.${slug}` : null
}
